=== Nexword/STEproject/TaskSet.dtd
<!ELEMENT task-set (task*)>
<!ATTLIST task-set
id ID #REQUIRED>

<!ELEMENT task (question, (single-answer | multiple-answer | matching-answer | open-answer | single-semiopen-answer | multiple-semiopen-answer))>
<!ATTLIST task
id ID #REQUIRED>

<!ELEMENT question EMPTY>
<!ATTLIST question
key IDREF  #REQUIRED>

<!ELEMENT single-answer (option+)>
<!ELEMENT multiple-answer (option+)>
<!ELEMENT open-answer (open-option)>
<!ELEMENT single-semiopen-answer (option+, open-option)>
<!ELEMENT multiple-semiopen-answer (option+, open-option+)>
<!ELEMENT matching-answer (matches, slots)>

<!ELEMENT matches (option+)>
<!ELEMENT slots (option+)>

<!ELEMENT option EMPTY>
<!ATTLIST option
key IDREF #REQUIRED>

<!ELEMENT open-option EMPTY>
<!ATTLIST open-option
key IDREF #REQUIRED>

=== Nexword/STEproject/TaskSet.xml
<!DOCTYPE task-set PUBLIC "-//STE//Logical//1//TaskSet" "http://www.ste.org/docs/0.1/xml/dtd/TaskSet.dtd">

<task-set id='###'>
	<task id='###'>
		<question key='####' />
		<single-answer>
			<option key='####' />
			<option key='####' />
			<option key='####' />
		</single-answer>
	</task>
	<task id='###'>
		<question key='####' />
		<multiple-answer>
			<option key='####' />
			<option key='####' />
			<option key='####' />
			<option key='####' />
		</multiple-answer>
	</task>
	<task id='###'>
		<question key='####' />
		<matching-answer>
			<matches>
				<option key='####' />
				<option key='####' />
				<option key='####' />
				<option key='####' />
				<option key='####' />
			</matches>
			<slots>
				<option key='####' />
				<option key='####' />
				<option key='####' />				
			</slots>
		</matching-answer>
	</task>
	<task id='###'>
		<question key='####' />
		<open-answer>
			<open-option key='####' />
		</open-answer>
	</task>
		<task id='###'>
		<question key='####' />
		<single-semiopen-answer>
			<option key='####' />
			<option key='####' />
			<option key='####' />
			<option key='####' />
			<open-option key='####' />
		</single-semiopen-answer>
	</task>
		<task id='###'>
		<question key='####' />
		<multiple-semiopen-answer>
			<option key='####' />
			<option key='####' />
			<option key='####' />
			<option key='####' />
			<open-option key='####' />
			<open-option key='####' />
		</multiple-semiopen-answer>
	</task>
</task-set>
