=== Nexword/STEproject/TestSet.dtd
<!ELEMENT test-set (test*)>
<!ATTLIST test-set 
id ID #REQUIRED>

<!ELEMENT test (note?, block+)>
<!ATTLIST test 
id ID #REQUIRED>

<!ELEMENT block (note?, task+)>
<!ATTLIST block
id ID #REQUIRED>

<!ELEMENT note EMPTY>
<!ATTLIST note
key IDREF #REQUIRED>

<!ELEMENT task EMPTY>
<!ATTLIST task
key IDREF #REQUIRED>

=== Nexword/STEproject/TestSet.xml
<!DOCTYPE test-set PUBLIC "-//STE//Logical//1//TestSet" "http://www.ste.org/docs/0.1/xml/dtd/TestSet.dtd">

<test-set id='###'>
	<test id='###'>
		<note key='####' />
		<block id='###'>
			<note key='####' />
			<task key='####' />	
			<task key='####' />
		</block>		
		<block id='###'>
			<task key='####' />	
			<task key='####' />
		</block>
	</test>
</test-set>
